### ISSUE TITLE
Can't run backend

### ISSUE THREAD

**Issue by sirPhoebus** [ShadovvBeast/TalkGPT#4]
Tried node 18.11 and even 19.4 but I got this:

TypeError: Failed to parse URL from undefined/json/version
    at Object.fetch (node:internal/deps/undici/undici:11118:11)
    at async getChromeEndpoint (file:///c:/zone/TalkGPT/dist/puppeteer.js:12:29)
    at async Module.initSession (file:///c:/zone/TalkGPT/dist/puppeteer.js:28:22)
    at async file:///c:/zone/TalkGPT/dist/index.js:23:1 {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:393:5)
      at URL.onParseError (node:internal/url:565:9)
      at new URL (node:internal/url:645:5)
      at new Request (node:internal/deps/undici/undici:9472:25)
      at Agent.fetch2 (node:internal/deps/undici/undici:10291:25)
      at Object.fetch (node:internal/deps/undici/undici:11116:28)
      at fetch (node:internal/process/pre_execution:216:25)
      at getChromeEndpoint (file:///c:/zone/TalkGPT/dist/puppeteer.js:12:35)
      at async Module.initSession (file:///c:/zone/TalkGPT/dist/puppeteer.js:28:22)
      at async file:///c:/zone/TalkGPT/dist/index.js:23:1 {
    input: 'undefined/json/version',
    code: 'ERR_INVALID_URL'
  }
}

I just ran : yarn build (which is OK) and then yarn start

Any ideas ?

**Comment by ShadovvBeast** [comment]
yes, you need to have a CHROME_ENDPOINT_URL env var configured with a url to a chrome remote debugger.
you can get this by running chrome --remote-debugging-port=9222, and then set CHROME_ENDPOINT_URL=http://localhost:9222

**Comment by ShadovvBeast** [comment]
Moreover, I recommend you try the pawan api in the new version I pushed today, instead of the CHROME_ENDPOINT_URL, use another env var: CHATGPT_SESSION_TOKEN, that should be populated with the session token from chatgpt itself (can be found in the cookies), it seems to work far better
