### ISSUE TITLE
Client error on first use

### ISSUE THREAD

**Issue by markNZed** [ShadovvBeast/TalkGPT#7]
Hi, after following the instructions I see this error in the client Javascript console. I am not familiar with React so not sure what d odo from here. I guess you've seen the chatGPT API is available now and they also announced a Whisper API that might fir well with this project.

```react-dom.development.js:14887 Uncaught Error: Objects are not valid as a React child (found: object with keys {role, id, parentMessageId, conversationId, text, detail}). If you meant to render a collection of children, use an array instead.
    at throwOnInvalidObjectType (react-dom.development.js:14887:9)
    at reconcileChildFibers2 (react-dom.development.js:15828:7)
    at reconcileChildren (react-dom.development.js:19174:28)
    at updateHostComponent (react-dom.development.js:19924:3)
    at beginWork (react-dom.development.js:21618:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)```

**Comment by markNZed** [comment]
After addressing the API in the other issue I get a first response then the client is empty. I need to reload the page to interact again.

**Comment by ShadovvBeast** [comment]
Unable to reproduce, if it still happens in the latest version, please reopen the issue

**Comment by markNZed** [comment]
Now seeing: `Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON` in the client
